import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Poppins, Roboto, Rubik } from 'next/font/google'

const poppins = Poppins({ weight: ['400', '600'], subsets: ['latin'], variable: '--font-poppins' })
const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'], variable: '--font-roboto' })
const rubik = Rubik({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-rubik' })

export const metadata: Metadata = {
  title: "To Do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto.variable} ${rubik.variable}`}>
      <body className="bg-gray-100 font-sans">
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
